optionsFile:
printHelp: false
appClassPath:
  - /home/byx/testSpace/javaprjs/sablecc-3.2/bin
mainClass: org.sablecc.sablecc.SableCC
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: /home/byx/testSpace/javaprjs/sablecc-3.2/taie-output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile:
analyses:
  pta: cs:1-call;
  cg: algorithm:pta;dump:true;dump-methods:true;dump-call-edges:true;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
classPath:
  - /home/byx/testSpace/javaprjs/.lib
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/resources.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/charsets.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/jce.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/management-agent.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/jsse.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.8/rt.jar
