optionsFile:
printHelp: false
appClassPath:
  - /home/byx/testSpace/javaprjs/jgrapht-0.8.1/bin
mainClass: org.jgrapht.demo.JGraphAdapterDemo
inputClasses: []
javaVersion: 6
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: /home/byx/testSpace/javaprjs/jgrapht-0.8.1/taie-output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile:
analyses:
  pta: cs:1-call;
  cg: algorithm:pta;dump:true;dump-methods:true;dump-call-edges:true;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
classPath:
  - /home/byx/testSpace/javaprjs/.lib
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.6/jce.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.6/jsse.jar
  - /home/byx/projects/Tai-e/java-benchmarks/JREs/jre1.6/rt.jar
