optionsFile:
printHelp: false
appClassPath:
  - /home/byx/testSpace/javaprjs/soot/2.3.0/sootclasses-2.3.0.jar
mainClass: soot.Main
inputClasses: []
javaVersion: 6
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: /home/byx/testSpace/javaprjs/soot/cha-output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile:
analyses:
  cg: algorithm:cha;dump-methods:true;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
classPath:
  - /home/byx/testSpace/javaprjs/soot/2.3.0/JFlex.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/java_cup.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/jasminclasses-2.3.0.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/pao.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/sootclasses-2.3.0.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/polyglot.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/coffer.jar
  - /home/byx/testSpace/javaprjs/soot/2.3.0/pth.jar
