optionsFile: null
printHelp: false
classPath:
- ../../testSpace/javaprjs/chart/chart-deps.jar
appClassPath:
- ../../testSpace/javaprjs/chart/chart.jar
mainClass: Harness
inputClasses: []
javaVersion: 6
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: ../../testSpace/javaprjs/chart/cha-output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  cg: algorithm:cha;dump-methods:true;
onlyGenPlan: false
keepResult:
- $KEEP-ALL
